version: '3.2'
services:
################################################################################
# Dashboard Client e2e tests
################################################################################
  # dashboard-client-e2e:
  #   build:
  #     context: ./dashboard-client-v1
  #     dockerfile: Dockerfile.e2e
  #   volumes:
  #     - ./dashboard-client-v1:/dashboard-client-e2e
  #   environment:
  #     CYPRESS_TARGET_HOST: localhost
  #     CYPRESS_TARGET_PORT: 4321
################################################################################
# Dashboard Client
################################################################################
  dashboard-client:
    build:
      context: ./dashboard-client-v1
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
    volumes:
      - ./dashboard-client-v1:/dashboard-client
    environment:
      PORT: "4321"
    # command: yarn start
